### ISSUE TITLE
Can not find newrelic.so module after installing on Alpine

### ISSUE THREAD

**Issue by rvanlaak** [newrelic/newrelic-php-agent#383] opened 2022-03-11 15:58 UTC
When installing the PHP Agent manually (e.g. not via package manager, but via .tar.gz) on Alpine it after installation can not find the module.

## Description

The newrelic.so module does seem to be located at the modules directory, but there are errors when trying to run php.

Manually sshing in the Docker image that gets build to run the installation manually leads to the same result.

Worth mentioning; the warning (see below) includes "Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20210902/**newrelic.so.so**"

## Steps to Reproduce

The installation script used (as suggested by the documentation) in the Dockerfile:

```
RUN cd ~ \
    && export NEWRELIC_VERSION="$(curl -sS https://download.newrelic.com/php_agent/release/ | sed -n 's/.*>\(.*linux-musl\).tar.gz<.*/\1/p')" \
    && curl -sS "https://download.newrelic.com/php_agent/release/${NEWRELIC_VERSION}.tar.gz" | gzip -dc | tar xf - \
    && cd "${NEWRELIC_VERSION}" \
    && NR_INSTALL_USE_CP_NOT_LN=true NR_INSTALL_SILENT=true ./newrelic-install install \
    && cd .. \
    && unset NEWRELIC_VERSION \
    && sed -i \
        -e "s/;\?newrelic.enabled =.*/newrelic.enabled = ${NEW_RELIC_ENABLED}/" \
        -e "s/newrelic.license =.*/newrelic.license = ${NRIA_LICENSE_KEY}/" \
        -e "s/newrelic.appname =.*/newrelic.appname = ${APP_NAME}/" \
        -e "s/newrelic.daemon.logfile =.*/newrelic.daemon.logfile = \/app\/var\/log\/newrelic-daemon\.log/" \
        -e "s/;\?newrelic.daemon.address =.*/newrelic.daemon.address = \/app\/var\/cache\/\.newrelic\.sock/" \
        -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
        -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
        /usr/local/etc/php/conf.d/newrelic.ini
```

## Expected Behavior

Module should get found when running `php -v` after installation.

## Relevant Logs / Console output

The actual warning when running `php -v`:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so (Error relocating /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so: unsupported relocation type 7), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so.so (**Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20210902/newrelic.so.so**: No such file or directory)) in Unknown on line 0
>
> PHP 8.1.2 (cli) (built: Jan 21 2022 21:44:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

## Your Environment

Docker image with `php:8.1-fpm-alpine` as base image.

## Additional context

![image](https://user-images.githubusercontent.com/2707563/157901065-6a47bef7-f5aa-4cd3-977d-0c46571d996a.png)

**Comment by zsistla** [comment] 2022-03-11 18:38
Hi @rvanlaak ,

Thanks for reaching out and providing so many details.  It really helped us reproduce the problem quickly.

The issue appears to be with these two lines:
```
        -e "s/newrelic.daemon.logfile =.*/newrelic.daemon.logfile = \/app\/var\/log\/newrelic-daemon\.log/" \
        -e "s/;\?newrelic.daemon.address =.*/newrelic.daemon.address = \/app\/var\/cache\/\.newrelic\.sock/" \
```

When we ran a dockerfile with your code snippet, those two lines failed since `/app/var` did not exist.
When we removed those two lines entirely, the daemon logfile defaulted to `/var/log/newrelic/newrelic-daemon.log` 
and the address defaulted to the abstract socket `@newrelic`.
After the removal, the Dockerfile was able to compile and the agent/daemon were able to send data to the New Relic backend.

Here's the complete dockerfile we used:
```
FROM php:8.1-fpm-alpine

#emulate customer environment
ENV NRIA_LICENSE_KEY <<REDACTED THIS VALUE WILL NEED TO BE SET IN ENV>>
ENV APP_NAME '8.1 alpine v1'
ENV NEW_RELIC_ENABLED true

RUN apk add sudo

RUN cd ~ \
    && export NEWRELIC_VERSION="$(curl -sS https://download.newrelic.com/php_agent/release/ | sed -n 's/.*>\(.*linux-musl\).tar.gz<.*/\1/p')" \
    && curl -sS "https://download.newrelic.com/php_agent/release/${NEWRELIC_VERSION}.tar.gz" | gzip -dc | tar xf - \
    && cd "${NEWRELIC_VERSION}" \
    && NR_INSTALL_SILENT=true ./newrelic-install install \
    && cd .. \
    && unset NEWRELIC_VERSION \
    && sed -i \
        -e "s/;\?newrelic.enabled =.*/newrelic.enabled = ${NEW_RELIC_ENABLED}/" \
        -e "s/newrelic.license =.*/newrelic.license = ${NRIA_LICENSE_KEY}/" \
        -e "s/newrelic.appname =.*/newrelic.appname = ${APP_NAME}/" \
        -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
        -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
        /usr/local/etc/php/conf.d/newrelic.ini
```

Please let us know if this resolves your issue.

**Comment by rvanlaak** [comment] 2022-03-12 09:24
Thank you so much for the quick reply. Did check it, and unfortunately that did not fix it. Please note that my platform is the Apple Macbook Pro 2020 with the M1 arm64 processor

With the following Dockerfile I do get the same "not found" warning.:

```Dockerfile
FROM composer:2 as builder
WORKDIR /app
VOLUME /tmp

COPY composer.* /app/
COPY .env* /app/
COPY bin/console /app/bin/
ADD config /app/config
ADD src /app/src
ADD public /app/public

RUN composer install --no-interaction --no-scripts --ignore-platform-reqs --no-dev --optimize-autoloader

FROM php:8.1-fpm-alpine as app
WORKDIR /app

# Environment arguments as retrieved from the docker-compose build args
ARG APP_NAME=${APP_NAME:-''}
ARG TIMEZONE=${TIMEZONE:-'Europe/Amsterdam'}
ARG OPCACHE_VALIDATE_TIMESTAMPS=${OPCACHE_VALIDATE_TIMESTAMPS:-1}
ARG NEW_RELIC_ENABLED=${NEW_RELIC_ENABLED:-0}
ARG NRIA_LICENSE_KEY=${NRIA_LICENSE_KEY:-''}

RUN set -xe  \
    && apk add --no-cache --update --virtual .phpize-deps $PHPIZE_DEPS \
    && pecl install -o -f redis \
    && echo "extension=redis.so" >/usr/local/etc/php/conf.d/redis.ini \
    && rm -rf /usr/share/php \
    && rm -rf /tmp/* \
    && apk del .phpize-deps $PHPIZE_DEPS

RUN touch /usr/local/var/log/php-fpm-error.log

RUN apk add --no-cache tzdata oniguruma-dev icu-dev libxml2-dev \
    && cp /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
    && echo "$TIMEZONE" >/etc/timezone \
    && apk del tzdata \
    && docker-php-ext-install pdo pdo_mysql opcache pcntl intl xml xmlwriter && docker-php-ext-enable opcache

# New Relic Install, and automated version of the instructions at https://docs.newrelic.com/docs/agents/php-agent/installation/php-agent-installation-tar-file
# configures some of the .ini values to use environment variables
RUN cd ~ \
    && export NEWRELIC_VERSION="$(curl -sS https://download.newrelic.com/php_agent/release/ | sed -n 's/.*>\(.*linux-musl\).tar.gz<.*/\1/p')" \
    && curl -sS "https://download.newrelic.com/php_agent/release/${NEWRELIC_VERSION}.tar.gz" | gzip -dc | tar xf - \
    && cd "${NEWRELIC_VERSION}" \
    && NR_INSTALL_USE_CP_NOT_LN=true NR_INSTALL_SILENT=true ./newrelic-install install \
    && cd .. \
    && unset NEWRELIC_VERSION \
    && sed -i \
        -e "s/;\?newrelic.enabled =.*/newrelic.enabled = ${NEW_RELIC_ENABLED}/" \
        -e "s/newrelic.license =.*/newrelic.license = ${NRIA_LICENSE_KEY}/" \
        -e "s/newrelic.appname =.*/newrelic.appname = ${APP_NAME}/" \
        -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
        -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
        /usr/local/etc/php/conf.d/newrelic.ini

USER www-data

# Get the built project from the builder stage
COPY --from=builder /app/* /app/
COPY --from=builder /usr/bin/composer /usr/bin/composer
```

**Comment by rvanlaak** [comment] 2022-03-12 11:33
The follow repo is a reproducer for me having the warning: https://github.com/rvanlaak/newrelic-php-agent-mac-m1

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/2707563/158016370-7589b9e7-b301-4015-8bd6-19524383dfc7.png">

**Comment by crishoj** [comment] 2022-04-01 00:03
@a-james-faria @aepuls @alanwest @alexkroman @am @ ZNeumann — please forgive me for this brazen mention.

Your paying customers are currently left with a dysfunctional agent for PHP, which doesn't report exceptions, and the official response so far is that support for Laravel only extends to version 7, which had end-of-life over a year ago.

Please consider devoting resources to this issue. A lack of consistent exception reporting defats the purpose of instrumentation.

**Comment by rvanlaak** [comment] 2022-04-01 10:22
@crishoj I did get an email notification about you having placed a comment on this issue last night, but I can not see it appearing anymore. Does that mean it was removed by the NewRelic team?

**Comment by rvanlaak** [comment] 2022-04-01 10:24
@zsistla can you follow-up on this issue? We even made a reproducer repository for NewRelic to easily reproduce the behaviour we are facing.

**Comment by crishoj** [comment] 2022-04-01 11:41
@rvanlaak — my apologies, I posted in the wrong thread. Moved it here: https://github.com/newrelic/newrelic-php-agent/issues/387#issuecomment-1085249668

**Comment by zsistla** [comment] 2022-04-04 04:43
Hi @rvanlaak ,

Thanks so much for the snippets and reproducer; they always help narrow down the issue.
We see you are using the M1 arm64 processor.
We do support the arm64 architecture; however, we currently only support it via building from source.
We do not yet have binaries for the agent or daemon.
Please see here for more details:
https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/

**Comment by zsistla** [comment] 2022-04-04 13:45
Yes, apologies for this as that is a bug with our installer: https://github.com/newrelic/newrelic-php-agent/issues/397
It will try to install the amd64 compatible binary on an arm64 architecture.

The binary that gets installed is not compatible with arm64 as we don't compile and package those binaries into the tarballs yet.

**Comment by devwithu** [comment] 2022-05-22 07:48
`root@free:~# uname -a
Linux free 5.13.0-1028-oracle #33~20.04.1-Ubuntu SMP Mon May 2 03:56:22 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux

root@free:~# 
root@free:~# dpkg --print-architecture 
arm64
root@free:~# 
root@free:~# arch
aarch64
root@free:~# 
root@free:~# php -v
PHP Warning:  PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/lib/php/20210902/newrelic.so (/usr/lib/php/20210902/newrelic.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/newrelic.so.so (/usr/lib/php/20210902/newrelic.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP 8.1.6 (cli) (built: May 17 2022 16:48:09) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.6, Copyright (c), by Zend Technologies`

is there any workaround ?

**Comment by renepenner** [comment] 2022-10-17 14:24
I have the same issue on my Mac with an Intel CPU ... is they are any solution yet?

**Comment by renepenner** [comment] 2022-10-18 08:27
I found a solution for me:

`RUN apk add  libc6-compat \
    && ln -s /lib/libc.musl-x86_64.so.1 /lib/ld-linux-x86-64.so.2`

**Comment by sweepchild** [comment] 2022-10-30 11:49
In my case that worked fine;
`RUN apk add gcompat`

**Comment by rvanlaak** [comment] 2022-12-01 12:38
We now took another approach; instead of using `sed` we copy our own `newrelic.ini` over the file in conf.d:

```dockerfile
COPY ./docker/php/newrelic.ini /usr/local/etc/php/conf.d/newrelic.ini
```
 ```ini
extension = "newrelic.so"
[newrelic]
newrelic.enabled = ${NEW_RELIC_ENABLED}
newrelic.appname = ${APP_NAME}
newrelic.license = ${NEW_RELIC_LICENSE_KEY}
```

This does properly work, but the problem we faced with that relates to the warning @devwithu also gets:

> PHP Warning: PHP Startup: Unable to load dynamic library 'newrelic.so' (tried: /usr/lib/php/20210902/newrelic.so (/usr/lib/php/20210902/newrelic.so: cannot open shared object file: No such file or directory), /usr/lib/php/20210902/newrelic.so.so (/usr/lib/php/20210902/newrelic.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Given that NR Agent does not allow installing the agent and extension on ARM, we make the installation conditional and do not install it on `dev` environments. Docker does not allow a `COPY` command to be conditional in a clean way, so the `newrelic.ini` file still gets copied.

We solved the warning above by removing the first line from the `newrelic.ini`, so the config is there but php will not load it. We consider splitting configuration and instantiation a good practice. 

Given that PHP still has to get instructed to load / enable the newrelic extension, we expected this conditional enable to work. The problem is, it doesn't:

```dockerfile
ARG NEWRELIC_ENABLED=1
RUN if [ "$NEWRELIC_ENABLED" = "1" ] ; then \
     docker-php-ext-enable newrelic \
fi
```

The cli output `php --ini " grep newrelic.enabled` does not state that the extension is enabled, while it is when the 1st line is kept intact on the `newrelic.ini`. 

We want to keep configuration and activation separate. How can we enable the newrelic extension after installation without putting the extension definition in the configuration?

**Comment by rvanlaak** [comment] 2023-06-16 08:02
The most important issue is that no exception is thrown or error code is returned while having an erroneous installation. Please do not silence failures.

**Comment by zsistla** [comment] 2023-09-21 15:09
Original issue that newrelic.so is not found on arm64 was resolved by addition of arm64 binaries.
Issue of silent failures when NR_INSTALL_SILENT option is selected is detailed in another issue: https://github.com/newrelic/newrelic-php-agent/issues/635

**Closed by zsistla** 2023-09-21 15:09 UTC
Labels: bug, enhancement, more info requested
