### ISSUE TITLE
Duplicate newrelic.ini file on Ubuntu Linux causes PHP Warning

### ISSUE THREAD

**Issue by neilpdx** [newrelic/newrelic-php-agent#598] opened 2023-01-20 19:13 UTC
## Description

When the agent is installed in Ubuntu Linux, the system creates a duplicate copy of the `newrelic.ini` prefixed with `20-`. When running PHP scripts, we get the error:

```
PHP Warning:  Module "newrelic" is already loaded in Unknown on line 0
```

It's also unclear which of these files is the correct one to edit, leading to confusion when configuring the agent or daemon.

## Steps to Reproduce

1. Install the agent on Ubuntu Linux
2. Run `php -i | grep newrelic.ini`
3. Note the above Warning occurs and there are two results for the .ini: `newrelic.ini` and `20-newrelic.ini`. 

## Expected Behavior

`20-newrelic.ini` should not exist on the system.

## Relevant Logs / Console output

```
php -i | grep newrelic.ini
PHP Warning:  Module "newrelic" is already loaded in Unknown on line 0
/etc/php/8.1/cli/conf.d/20-newrelic.ini,
/etc/php/8.1/cli/conf.d/newrelic.ini
```

## Your Environment

Ubuntu Linux 20.04.3 / PHP 8.1

**Comment by bduranleau-nr** [comment] 2023-01-20 19:48
Duplicate of #399

**Closed by bduranleau-nr** 2023-01-20 19:48 UTC
Labels: bug

**Comment by lavarou** [comment] 2023-08-23 18:23
@neilpdx How was the PHP 8.1 installed on Ubuntu-20.04: from source, from apt repository, other method? How was the PHP Agent installed: from source, from tarball, from apt repository? Could you include the steps used to install PHP and PHP Agent in the steps to reproduce? This would be much appreciated and very helpful in troubleshooting this issue.
