### ISSUE TITLE
PHP 8.3

### ISSUE THREAD

**Issue by ruudk** [newrelic/newrelic-php-agent#676] opened 2023-06-08 19:37 UTC
Since https://github.com/newrelic/newrelic-php-agent/issues/616 is locked as spam for whatever reason here an update: Alpha 1 of PHP 8.3 is released. Time to start testing.

**Comment by rvanlaak** [comment] 2023-07-28 14:05
Beta.1 has been released two days ago, meaning the API now is stable and won't break anymore! https://externals.io/message/120863

**Comment by rvanlaak** [comment] 2023-07-28 14:08
What I'd like to prevent to see happening is that people will lose their tracking when they would update their PHP installations; given that the agent installation won't fail when an unsupported version is found ([see related issue](https://github.com/newrelic/newrelic-php-agent/issues/635)),

**Comment by rvanlaak** [comment] 2023-09-16 15:31
Release Candiate 2 was released: https://www.php.net/archive/2023.php#2023-09-14-1

As expected, and as in previous RCs; no BC breaks regarding the minor's features on the changelist: https://github.com/php/php-src/blob/php-8.3.0RC2/NEWS

**Comment by ruudk** [comment] 2023-10-04 07:03
This makes me happy. Nice work New Relic 💪 💙

**Comment by ruudk** [comment] 2023-11-21 09:04
PHP 8.3 will be released in 2 days: November 23, 2023. 

@zsistla @mfulb @bduranleau-nr Any news? Can we upgrade on day 0?

**Comment by rvanlaak** [comment] 2023-11-21 13:46
No. ObserverAPI hasn't been finished nor merged yet.

Refs:
* https://github.com/newrelic/newrelic-php-agent/pull/737#issuecomment-1816474453
* https://github.com/newrelic/newrelic-php-agent/pull/542

**Comment by alies-dev** [comment] 2023-11-22 18:32
PHP 8.3 release is tomorrow. Features announcement: https://www.php.net/releases/8.3/en.php

I hope this time it will be without a drama caused by 3+ month delay of the newrelic php agent 🤞

**Comment by rvanlaak** [comment] 2023-11-27 10:14
Congratulations on the general release everyone! 🎉   https://www.php.net/archive/2023.php#2023-11-23-2

**Comment by elomonaco** [comment] 2023-11-29 20:24
Sounds like for the time being, I need to stay on PHP 8.2 to keep new relic running, hoping they add PHP 8.3 sooner rather than later. Hopefully they learned their lesson from the last two PHP releases to not drag it out and piss off customers who like to stay current with their PHP version.

**Comment by AceXintense** [comment] 2023-12-06 17:51
Bump, This really should have been worked on for the months that PHP 8.3 is being beta tested. NR please can you make this a priority to support new versions of PHP especially when the version is not that different...

I shouldn't have to postpone updating PHP because the agent is not being actively supported on the latest version.

**Comment by rvanlaak** [comment] 2023-12-07 17:35
Dear friends at NewRelic ❤️ , can you please once and for all stop removing constructive comments on issues and marking issues as spam. Github is an open collaboration platform, and the fact that for two years already NewRelic employees [Today continued with removing comments again for unclear reasons](https://github.com/newrelic/newrelic-php-agent/pull/737#event-11184109419) is continuing to get extremely worrying. 

<img width="750" alt="image" src="https://github.com/newrelic/newrelic-php-agent/assets/2707563/66156212-e30c-4975-8203-e2b2fcd2177f">

If there is the need to remove comments, please explain why you do so and / or refer to a policy that has been put in place. In addition, the comment that @andypost left on the PHP 8.3 draft PR was providing extremely valuable information on what apparently PHPs ObserverAPI is about, and why NewRelic would want to implement it. Although it links your competitor's blogpost he is not even affiliated with Datadog whatsoever. NewRelic itself never has been providing any information about ObserverAPI, that does not give the right to remove comments of which the intention was positive.

<img width="756" alt="image" src="https://github.com/newrelic/newrelic-php-agent/assets/2707563/2bd586b7-a7cc-4c31-9edd-aa09ff9192f7">

With this rude approach, NewRelic is burning the credits of a friendly community that for several years in a row has expressed that it is eager to help with testing or whatsoever.

**Comment by andypost** [comment] 2023-12-07 19:13
Sadly there's not a lot of information about new API and it's strange that my comment was removed. Maybe because my comment has wording about other competitors...

**Comment by ak-war** [comment] 2023-12-07 20:29
Php 8.3 is the current focus of our team, the OAPI dependency is removed for now.
8.3 support for OAPI will be included subsequently, this change in priority is to allow a quicker timeline to support 8.3.
In an effort to focus on the release and prevent misinformation, we will be locking this thread.

**Comment by Ak-x** [comment] 2023-12-20 22:31
Closing per: https://github.com/newrelic/newrelic-php-agent/releases/tag/v10.15.0.4

**Closed by Ak-x** 2023-12-20 22:31 UTC
Labels: enhancement
