### ISSUE TITLE
PHP8 MMF#1: Install agent in PHP8 w/o faults

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-php-agent#33] opened 2020-11-20 01:24 UTC
The outcome of this work is ability to use the PHP agent in an PHP 8 environment without crashes and to clearly document how to configure a PHP 8 service to be used with this base bones PHP8 support in our PHP agent.

This is part of multiple MMFs for PHP 8 work as outlined below.

#33  MMF#1 [<ins>Agent with PHP 8 support </ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.hx9v342k5zzq)
#32 MMF#2 [<ins>Build Environment with PHP 8.0</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.oa5sk1ovziy)
#34 MMF#3 [<ins>Update Agent Tests with PHP 8.0 </ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.p2q7qbb5pbkr)
#35 MMF#4 [<ins>Release Agent with PHP 8.0 Support</ins>](https://docs.google.com/document/d/1iolwPOyr1AcOmUDqzf5ZQZ4ODm1m593onSRhFP-UhiY/edit#heading=h.et7wy5raaa9)

**Comment by tomfotherby** [comment] 2020-12-21 19:05
We have delayed the rollout of PHP 8 on our fleet of webservers, waiting for support from the NewRelic PHP Agent. (Commented to ensure the `stale` :robot: knows this issue should be active)

**Comment by kneitinger** [comment] 2020-12-22 21:00
Hi @tomfotherby!

Thanks for the interest, and clever stalebot hacking :slightly_smiling_face: (I believe we've made some changes that make stalebot less eager in the future).

I'm closing this ticket, since it was designed for use to track work on all of the _code_ adjustments that were needed for PHP-8 support.  We have a few more phases to complete before we have a well-tested production-ready release, so I recommended watching #35 for a more helpful status indicator.

Take care!

**Closed** 2020-12-22 21:02 UTC
Labels: epic
