### ISSUE TITLE
Cannot build agent from main (`/tmp/newrelic-php-agent/daemon/go.mod:3: invalid go version '1.21.1': must match format 1.23`)

### ISSUE THREAD

**Issue by WarcraftYax** [newrelic/newrelic-php-agent#860] opened 2024-03-19 18:09 UTC
As far as I understand, the version specified in `daemon/go.mod` is in an invalid format: https://github.com/newrelic/newrelic-php-agent/commit/9caf27b1bcd6ce58da28365b7a517180ad4a4d53#diff-fb123b2d60ee4889a2428abfc5aff499150e74a5d11da01ddfa842a582991497R3

Instead of `1.21.1`, it should be `1.21`.

Trying to build from source starting from AWS AMI `aws-elasticbeanstalk-amzn-2023.3.20240219.64bit_arm-eb_php82_amazon_linux_2023-hvm-2024-02-20T20-55` with:

```
yum -y groupinstall "Development Tools"
yum -y install libcurl-devel openssl-devel pcre-devel pcre-static zlib-devel zlib-static php-devel golang
git clone https://github.com/newrelic/newrelic-php-agent.git
cd newrelic-php-agent
make all OPTIMIZE=1
```

results in the error:

`/tmp/newrelic-php-agent/daemon/go.mod:3: invalid go version '1.21.1': must match format 1.23`

**Comment by bduranleau-nr** [comment] 2024-03-20 17:36
Hi @WarcraftYax 

This message actually appears to be part of a bug in core Golang discussed in this [issue](https://github.com/golang/go/issues/61888) against the Golang repository and seems to be fixed by Golang in this [commit](https://cs.opensource.google/go/x/mod/+/master:modfile/rule.go;l=633-649;bpv=1;bpt=0;drc=766dc5df63e3e3e5cd6b1682f522a01c99723beb).

Typically, if you're seeing this message, it probably means you're using an older version of Go than the one specified in the `go.mod` file, so pre `1.21.1`. The latest updates to the Daemon require a minimum Go version of 1.21.1 if you want to build from source. Can you share the version of Go used in your build environment that is generating this error by running the `go version` command? 
The output should look something like this:
```
$ go version
go version go1.21.1 linux/arm64
```

I can confirm after running a build locally that I do not encounter this error when building using the Dockerized dev environment or building directly on go versions 1.21.1 and 1.21.6.

**Comment by WarcraftYax** [comment] 2024-03-20 17:44
Ah interesting, I didn't come across that nuance in my research - sorry!

The version of go available to Amazon Linux (from `yum install golang`) is `1.20.12-1.amzn2023.0.1`, so that makes sense.

I may have to do some extra steps to ensure that the version of go on my EC2 instance matches the version that New Relic expects. I'm currently replacing `1.21.1` to `1.20` in `daemon/go.mod` and `go.work` which is obviously less than ideal. I don't think anything needs to change on your end though now I understand this.

**Comment by bduranleau-nr** [comment] 2024-03-20 18:16
Are you attempting to build from source to get ARM architecture support? As of release 10.10, all NR PHP Agent releases contain support for install on ARM-architecture machines via the [tarball installation](https://docs.newrelic.com/docs/apm/agents/php-agent/installation/php-agent-installation-arm64/#tarball-installation) method (provided the version of PHP you are running against is >= 8.0).

**Comment by WarcraftYax** [comment] 2024-03-20 20:51
Yes, that is exactly our use case. So I may actually be able to clean out a lot of this and just install it directly now that's supported. Really appreciate you pointing that out! Should make life simpler 😄

**Comment by bduranleau-nr** [comment] 2024-03-20 21:36
Glad to hear it @WarcraftYax! Happy we could help.

**Closed** 2024-03-20 21:37 UTC
Labels: bug
